#!/usr/bin/env node
// Builds supabase/schema.sql by concatenating the migrations in numeric order — a
// single committed, reviewable view of the schema and the basis for a drift check.
// READ-ONLY over the repo; it never connects to or touches the database.
//
//   node scripts/build-schema.mjs          # (re)write supabase/schema.sql
//   node scripts/build-schema.mjs --check  # exit 1 if supabase/schema.sql is stale
//
// Wire `--check` into CI so a migration that isn't reflected in schema.sql fails the
// PR — the cheap first step of a real migration pipeline (overview: manual migrations
// are the root cause of the defensive retry-without-column code).

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const migDir = join(root, 'supabase', 'migrations');
const outFile = join(root, 'supabase', 'schema.sql');

const files = readdirSync(migDir)
  .filter((f) => f.endsWith('.sql'))
  .sort((a, b) => {
    const na = parseInt(a.slice(0, 3), 10);
    const nb = parseInt(b.slice(0, 3), 10);
    if (Number.isNaN(na) || Number.isNaN(nb) || na === nb) return a.localeCompare(b);
    return na - nb;
  });

const header =
  `-- AUTO-GENERATED by scripts/build-schema.mjs — do not edit by hand.\n` +
  `-- Concatenation of supabase/migrations/*.sql in numeric order (${files.length} files).\n` +
  `-- Regenerate: npm run db:schema\n\n`;

const body = files
  .map((f) => {
    const sql = readFileSync(join(migDir, f), 'utf8').replace(/\r\n/g, '\n').trimEnd();
    const bar = '-- ============================================================';
    return `${bar}\n-- ${f}\n${bar}\n${sql}\n`;
  })
  .join('\n');

const content = header + body;

if (process.argv.includes('--check')) {
  const current = existsSync(outFile) ? readFileSync(outFile, 'utf8').replace(/\r\n/g, '\n') : '';
  if (current !== content) {
    console.error('✗ supabase/schema.sql is stale. Run: npm run db:schema');
    process.exit(1);
  }
  console.log('✓ supabase/schema.sql is up to date.');
} else {
  writeFileSync(outFile, content);
  console.log(`✓ Wrote supabase/schema.sql from ${files.length} migrations.`);
}
